name: Deploy

on: 
  push:
      paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 'latest'
          cache: pnpm
      - name: Install package and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
          fqdn: yacd.yuuna.lol
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
